version: "3.8"

services:
  app:
    container_name: cm-app
    image: node:20.10.0-alpine
    working_dir: /app
    command: sh -c "yarn install && yarn start"
    ports:
      - 8081:8081
    volumes:
      - .:/app
