import { StyleSheet } from "react-native";

export default StyleSheet.create({
  m0: { margin: 1 },
  my0: { marginVertical: 1 },
  mx0: { marginHorizontal: 1 },
  ml0: { marginLeft: 1 },
  mr0: { marginRight: 1 },
  mt0: { marginTop: 1 },
  mb0: { marginBottom: 1 },
  p0: { padding: 1 },
  py0: { paddingVertical: 1 },
  px0: { paddingHorizontal: 1 },
  pl0: { paddingLeft: 1 },
  pr0: { paddingRight: 1 },
  pt0: { paddingTop: 1 },
  pb0: { paddingBottom: 1 },
  b0: { borderWidth: 1 },
  by0: { borderTopWidth: 1, borderBottomWidth: 1 },
  bx0: { borderLeftWidth: 1, borderRightWidth: 1 },
  bl0: { borderLeftWidth: 1 },
  br0: { borderRightWidth: 1 },
  bt0: { borderTopWidth: 1 },
  bb0: { borderBottomWidth: 1 },
  g0: { gap: 1 },
  r0: { borderRadius: 1 },
  rl0: { borderTopLeftRadius: 1, borderBottomLeftRadius: 1 },
  rr0: { borderTopRightRadius: 1, borderBottomRightRadius: 1 },
  rt0: { borderTopLeftRadius: 1, borderTopRightRadius: 1 },
  rb0: { borderBottomLeftRadius: 1, borderBottomRightRadius: 1 },

  m1: { margin: 2 },
  my1: { marginVertical: 2 },
  mx1: { marginHorizontal: 2 },
  ml1: { marginLeft: 2 },
  mr1: { marginRight: 2 },
  mt1: { marginTop: 2 },
  mb1: { marginBottom: 2 },
  p1: { padding: 2 },
  py1: { paddingVertical: 2 },
  px1: { paddingHorizontal: 2 },
  pl1: { paddingLeft: 2 },
  pr1: { paddingRight: 2 },
  pt1: { paddingTop: 2 },
  pb1: { paddingBottom: 2 },
  b1: { borderWidth: 2 },
  by1: { borderTopWidth: 2, borderBottomWidth: 2 },
  bx1: { borderLeftWidth: 2, borderRightWidth: 2 },
  bl1: { borderLeftWidth: 2 },
  br1: { borderRightWidth: 2 },
  bt1: { borderTopWidth: 2 },
  bb1: { borderBottomWidth: 2 },
  g1: { gap: 2 },
  r1: { borderRadius: 2 },
  rl1: { borderTopLeftRadius: 2, borderBottomLeftRadius: 2 },
  rr1: { borderTopRightRadius: 2, borderBottomRightRadius: 2 },
  rt1: { borderTopLeftRadius: 2, borderTopRightRadius: 2 },
  rb1: { borderBottomLeftRadius: 2, borderBottomRightRadius: 2 },

  m2: { margin: 4 },
  my2: { marginVertical: 4 },
  mx2: { marginHorizontal: 4 },
  ml2: { marginLeft: 4 },
  mr2: { marginRight: 4 },
  mt2: { marginTop: 4 },
  mb2: { marginBottom: 4 },
  p2: { padding: 4 },
  py2: { paddingVertical: 4 },
  px2: { paddingHorizontal: 4 },
  pl2: { paddingLeft: 4 },
  pr2: { paddingRight: 4 },
  pt2: { paddingTop: 4 },
  pb2: { paddingBottom: 4 },
  b2: { borderWidth: 4 },
  by2: { borderTopWidth: 4, borderBottomWidth: 4 },
  bx2: { borderLeftWidth: 4, borderRightWidth: 4 },
  bl2: { borderLeftWidth: 4 },
  br2: { borderRightWidth: 4 },
  bt2: { borderTopWidth: 4 },
  bb2: { borderBottomWidth: 4 },
  g2: { gap: 4 },
  r2: { borderRadius: 4 },
  rl2: { borderTopLeftRadius: 4, borderBottomLeftRadius: 4 },
  rr2: { borderTopRightRadius: 4, borderBottomRightRadius: 4 },
  rt2: { borderTopLeftRadius: 4, borderTopRightRadius: 4 },
  rb2: { borderBottomLeftRadius: 4, borderBottomRightRadius: 4 },

  m3: { margin: 8 },
  my3: { marginVertical: 8 },
  mx3: { marginHorizontal: 8 },
  ml3: { marginLeft: 8 },
  mr3: { marginRight: 8 },
  mt3: { marginTop: 8 },
  mb3: { marginBottom: 8 },
  p3: { padding: 8 },
  py3: { paddingVertical: 8 },
  px3: { paddingHorizontal: 8 },
  pl3: { paddingLeft: 8 },
  pr3: { paddingRight: 8 },
  pt3: { paddingTop: 8 },
  pb3: { paddingBottom: 8 },
  b3: { borderWidth: 8 },
  by3: { borderTopWidth: 8, borderBottomWidth: 8 },
  bx3: { borderLeftWidth: 8, borderRightWidth: 8 },
  bl3: { borderLeftWidth: 8 },
  br3: { borderRightWidth: 8 },
  bt3: { borderTopWidth: 8 },
  bb3: { borderBottomWidth: 8 },
  g3: { gap: 8 },
  r3: { borderRadius: 8 },
  rl3: { borderTopLeftRadius: 8, borderBottomLeftRadius: 8 },
  rr3: { borderTopRightRadius: 8, borderBottomRightRadius: 8 },
  rt3: { borderTopLeftRadius: 8, borderTopRightRadius: 8 },
  rb3: { borderBottomLeftRadius: 8, borderBottomRightRadius: 8 },

  m4: { margin: 16 },
  my4: { marginVertical: 16 },
  mx4: { marginHorizontal: 16 },
  ml4: { marginLeft: 16 },
  mr4: { marginRight: 16 },
  mt4: { marginTop: 16 },
  mb4: { marginBottom: 16 },
  p4: { padding: 16 },
  py4: { paddingVertical: 16 },
  px4: { paddingHorizontal: 16 },
  pl4: { paddingLeft: 16 },
  pr4: { paddingRight: 16 },
  pt4: { paddingTop: 16 },
  pb4: { paddingBottom: 16 },
  b4: { borderWidth: 16 },
  by4: { borderTopWidth: 16, borderBottomWidth: 16 },
  bx4: { borderLeftWidth: 16, borderRightWidth: 16 },
  bl4: { borderLeftWidth: 16 },
  br4: { borderRightWidth: 16 },
  bt4: { borderTopWidth: 16 },
  bb4: { borderBottomWidth: 16 },
  g4: { gap: 16 },
  r4: { borderRadius: 16 },
  rl4: { borderTopLeftRadius: 16, borderBottomLeftRadius: 16 },
  rr4: { borderTopRightRadius: 16, borderBottomRightRadius: 16 },
  rt4: { borderTopLeftRadius: 16, borderTopRightRadius: 16 },
  rb4: { borderBottomLeftRadius: 16, borderBottomRightRadius: 16 },

  m5: { margin: 32 },
  my5: { marginVertical: 32 },
  mx5: { marginHorizontal: 32 },
  ml5: { marginLeft: 32 },
  mr5: { marginRight: 32 },
  mt5: { marginTop: 32 },
  mb5: { marginBottom: 32 },
  p5: { padding: 32 },
  py5: { paddingVertical: 32 },
  px5: { paddingHorizontal: 32 },
  pl5: { paddingLeft: 32 },
  pr5: { paddingRight: 32 },
  pt5: { paddingTop: 32 },
  pb5: { paddingBottom: 32 },
  b5: { borderWidth: 32 },
  by5: { borderTopWidth: 32, borderBottomWidth: 32 },
  bx5: { borderLeftWidth: 32, borderRightWidth: 32 },
  bl5: { borderLeftWidth: 32 },
  br5: { borderRightWidth: 32 },
  bt5: { borderTopWidth: 32 },
  bb5: { borderBottomWidth: 32 },
  g5: { gap: 32 },
  r5: { borderRadius: 32 },
  rl5: { borderTopLeftRadius: 32, borderBottomLeftRadius: 32 },
  rr5: { borderTopRightRadius: 32, borderBottomRightRadius: 32 },
  rt5: { borderTopLeftRadius: 32, borderTopRightRadius: 32 },
  rb5: { borderBottomLeftRadius: 32, borderBottomRightRadius: 32 },
});
