export const GENRES = [
  { label: "Ação", value: 28 },
  { label: "Aventura", value: 12 },
  { label: "Animação", value: 16 },
  { label: "Comédia", value: 35 },
  { label: "Crime", value: 80 },
  { label: "Documentário", value: 99 },
  { label: "Drama", value: 18 },
  { label: "Família", value: 10751 },
  { label: "Fantasia", value: 14 },
  { label: "História", value: 36 },
  { label: "Terror", value: 27 },
  { label: "Música", value: 10402 },
  { label: "Mistério", value: 9648 },
  { label: "Romance", value: 10749 },
  { label: "Ficção científica", value: 878 },
  { label: "Cinema TV", value: 10770 },
  { label: "Thriller", value: 53 },
  { label: "Guerra", value: 10752 },
  { label: "Faroeste", value: 37 },
];
